export { default as Certificates } from "./Certificates.astro";
export { default as Complated } from "./Complated.astro";
export { default as Cycle } from "./Cycle.astro";
export { default as Faq } from "./Faq.astro";
export { default as Hero } from "./Hero.astro";
export { default as Letters } from "./Letters.astro";
export { default as Partners } from "./Partners.astro";
export { default as Stats } from "./Stats.astro";
export { default as Trust } from "./Trust.astro";
